//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BambinoProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientsTBL
    {
        public int Id { get; set; }
        public string clientName { get; set; }
        public string clientLastName { get; set; }
        public string clientPhone { get; set; }
        public string Email { get; set; }
        public string clientInstitutionSymbol { get; set; }
        public string paymentMethod { get; set; }
    }
}
