//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BambinoProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployesTBL
    {
        public int Id { get; set; }
        public string EmployedName { get; set; }
        public string EmployedLastName { get; set; }
        public string fullName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string NameOfTheBank { get; set; }
        public string BankBranchNumber { get; set; }
        public string BankAccountNumber { get; set; }
    }
}
