//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BambinoProj
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<prodExtraKeys> prodExtraKeys { get; set; }
        public virtual DbSet<productExtraData> productExtraData { get; set; }
        public virtual DbSet<productTBL> productTBL { get; set; }
        public virtual DbSet<productTypeTBL> productTypeTBL { get; set; }
        public virtual DbSet<productView> productView { get; set; }
    }
}
