//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BambinoProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class productView
    {
        public int Id { get; set; }
        public string prodName { get; set; }
        public string KeyName { get; set; }
        public string value { get; set; }
        public string typeName { get; set; }
        public int productID { get; set; }
        public int keyID { get; set; }
    }
}
