//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BambinoProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class productExtraData
    {
        public int Id { get; set; }
        public int productID { get; set; }
        public int keyID { get; set; }
        public string value { get; set; }
    
        public virtual prodExtraKeys prodExtraKeys { get; set; }
        public virtual productTBL productTBL { get; set; }
    }
}
