//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BambinoProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class prodExtraKeys
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prodExtraKeys()
        {
            this.productExtraData = new HashSet<productExtraData>();
        }
    
        public int Id { get; set; }
        public string KeyName { get; set; }
        public string KeyDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productExtraData> productExtraData { get; set; }
    }
}
